### ISSUE TITLE
getOrderList接口疑问

### ISSUE THREAD

**Issue by Mickyxing** [snowballsecurities/snowx-ss-api-java-sdk#4]
1.这个接口是否只能查询通过api的下单信息
2.为什么默认参数情况下会返回之前货币兑换的订单信息
3.想了解一下如果不传参数情况下OrderStatus 和SecurityType 默认参数是什么

**Comment by Mickyxing** [comment]
问题1修改：如何查询在手机app下单已完成的订单？

**Comment by chnyangjie** [comment]
订单查询接口可以获取所有的订单，但是撤单接口只能操作 API 下的订单
货币兑换是特殊订单类型，会一直在订单列表中
默认的Status是ALL，默认的SecurityType 是 ALL

**Comment by Mickyxing** [comment]
那订单查询接口是否限制只能查询最近一段时间的订单，我根据请求参数 OrderStatus = ALL ，securityType=[STK],发现返回的只有我今天的订单(包括通过api和app下单的订单），之前历史已经成交的订单没有返回，我在app上查询到我上一笔app历史订单是在20230613

**Comment by chnyangjie** [comment]
历史订单可以用成交列表的接口查询
